services:
  - type: web
    name: offline-code-runner
    env: docker
    plan: free
    region: singapore # Optional: chose a region near you or remove to default
    branch: master
    envVars:
      - key: PORT
        value: 10000
